/**
 * Sync GeoLibre's `deployment.json` schema and compile the validator.
 *
 *   npm run sync:schema -- ../GeoLibre   copy schema/deployment.schema.json from a
 *                                        GeoLibre checkout, record its commit in
 *                                        schema/SOURCE.json, regenerate the validator
 *   npm run sync:schema                  regenerate the validator from the committed
 *                                        schema (what CI checks)
 *
 * The validator is generated with Ajv's standalone mode so the app never
 * compiles a schema at runtime (which needs `new Function` and would break
 * under a strict Content-Security-Policy).
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const here = import.meta.dirname;
const schemaPath = resolve(here, "../schema/deployment.schema.json");
const sourcePath = resolve(here, "../schema/SOURCE.json");
const validatorPath = resolve(here, "../src/policy/schema-validator.generated.js");

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

const source = process.argv[2];
let schema: Record<string, any>;
let synced: string | undefined;

if (source) {
  const root = resolve(source);
  const file = join(root, "schema/deployment.schema.json");
  if (!existsSync(file)) fail(`No schema/deployment.schema.json in ${root}; pass a GeoLibre checkout.`);
  try {
    schema = JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    fail(`Can't parse ${file}: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (
    typeof schema.$id !== "string" ||
    !schema.$id.startsWith("https://raw.githubusercontent.com/opengeos/GeoLibre/")
  ) {
    fail(`${file} has $id ${JSON.stringify(schema.$id)}, not GeoLibre's; refusing to sync.`);
  }
  if (schema.properties?.version?.const !== 1) {
    fail(`${file} pins properties.version.const to ${JSON.stringify(schema.properties?.version?.const)}, but this app only writes version 1.`);
  }
  let commit = "unknown";
  try {
    commit = execFileSync("git", ["-C", root, "rev-parse", "--short", "HEAD"], {
      encoding: "utf8",
    }).trim();
  } catch {
    // Not a git checkout; keep "unknown".
  }
  writeFileSync(schemaPath, `${JSON.stringify(schema, null, 2)}\n`);
  writeFileSync(
    sourcePath,
    `${JSON.stringify({ repository: "opengeos/GeoLibre", commit }, null, 2)}\n`,
  );
  synced = commit;
} else {
  schema = JSON.parse(readFileSync(schemaPath, "utf8"));
}

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  allowUnionTypes: true,
  code: { source: true, esm: true },
});
const validate = ajv.compile(schema);
const banner =
  "// Generated by `npm run sync:schema` from schema/deployment.schema.json. Do not edit.\n";
// Ajv's ESM output still pulls its runtime helpers in with require(); hoist
// them into default imports so the module is plain ESM for Vite and Node.
const runtimeImports: string[] = [];
// CommonJS interop differs between bundlers and Node (the default import is
// either `module.exports` or `exports.default`), so accept both shapes.
const code = standaloneCode(ajv, validate).replace(
  /require\("([^"]+)"\)(\.default)?/g,
  (_, path: string, viaDefault: string | undefined) => {
    const name = `ajvRuntime${runtimeImports.length}`;
    runtimeImports.push(`import ${name} from "${path}.js";`);
    return viaDefault ? `(${name}.default ?? ${name})` : name;
  },
);
writeFileSync(validatorPath, `${banner}${runtimeImports.join("\n")}\n${code}`);

console.log(
  synced
    ? `Wrote ${schemaPath} and ${sourcePath} (GeoLibre ${synced}), and ${validatorPath}`
    : `Wrote ${validatorPath}`,
);
